import { useNavigate } from "react-router-dom";

export default function PrivacyPolicy() {
  const navigate = useNavigate();
  const EFFECTIVE = "April 11, 2026";
  const COMPANY = "OurSpace 2.0";
  const CONTACT = "privacy@ourspace.app";

  return (
    <div style={{ minHeight:"100vh",background:"#0d0d1a",color:"#f0f0f0",fontFamily:"'Segoe UI',sans-serif",padding:"24px 20px",maxWidth:700,margin:"0 auto" }}>
      <button onClick={()=>navigate(-1)} style={{ background:"transparent",border:"none",color:"#94a3b8",fontSize:14,cursor:"pointer",marginBottom:20 }}>← Back</button>
      <h1 style={{ fontWeight:900,fontSize:26,marginBottom:4,background:"linear-gradient(90deg,#c084fc,#22d3ee)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent" }}>Privacy Policy</h1>
      <p style={{ color:"#64748b",fontSize:13,marginBottom:28 }}>Effective: {EFFECTIVE} · {COMPANY}</p>

      {[
        ["1. Information We Collect", "We collect information you provide (name, email, profile content), information generated by your use (posts, messages, interactions), and technical data (device type, browser, IP address). We do not sell your personal information."],
        ["2. How We Use Your Information", "We use your information to operate and improve the Service, personalize your experience, send notifications you've opted into, respond to support requests, and comply with legal obligations. We do not use your data to train AI models without explicit consent."],
        ["3. Chronological Feed & No Profiling", "OurSpace 2.0 does not build algorithmic behavior profiles. Your feed is strictly chronological. We do not use your content consumption to manipulate what you see."],
        ["4. Data Sharing", "We do not sell your data. We may share data with service providers who help operate the platform (subject to confidentiality agreements), or if required by law. We will notify you of law enforcement requests unless prohibited."],
        ["5. End-to-End Encrypted Messages", "Messages you send via The Shield (E2EE) are encrypted on your device and cannot be read by us. We store only the encrypted ciphertext and metadata (sender, receiver, timestamp)."],
        ["6. Children's Privacy (COPPA)", "OurSpace 2.0 is not directed to children under 13. We do not knowingly collect personal information from children under 13. Users 13–17 require verifiable parental consent. If you believe a child under 13 has provided data, contact us at " + CONTACT + " and we will delete it promptly."],
        ["7. GDPR Rights (EU/EEA Users)", "If you are in the EU/EEA, you have the right to: access your personal data, correct inaccurate data, request deletion ('right to be forgotten'), restrict or object to processing, data portability, and lodge a complaint with your supervisory authority. Contact us at " + CONTACT + " to exercise these rights."],
        ["8. CCPA Rights (California Users)", "California residents have the right to know what personal data we collect, the right to delete personal data, the right to opt out of sale (we do not sell data), and the right to non-discrimination. Submit requests to " + CONTACT + "."],
        ["9. Data Retention", "We retain your data while your account is active and for 30 days after deletion, unless longer retention is required by law. Encrypted message content is deleted when you delete a conversation."],
        ["10. Security", "We use industry-standard encryption (TLS in transit, AES-256 at rest) and regular security audits. No system is 100% secure — report vulnerabilities to security@ourspace.app."],
        ["11. Cookies", "We use essential cookies for authentication and session management. We do not use third-party advertising or tracking cookies."],
        ["12. Changes to This Policy", "We will notify users of material changes via in-app notification or email at least 30 days before they take effect. Continued use constitutes acceptance."],
        ["13. Contact", "Privacy questions or data requests: " + CONTACT],
      ].map(([title, body]) => (
        <div key={title} style={{ marginBottom:24 }}>
          <h2 style={{ fontSize:15,fontWeight:700,color:"#22d3ee",marginBottom:8 }}>{title}</h2>
          <p style={{ color:"#94a3b8",fontSize:14,lineHeight:1.7,margin:0 }}>{body}</p>
        </div>
      ))}

      <div style={{ marginTop:32,padding:16,background:"#16162a",borderRadius:12,border:"1px solid #2a2a45",fontSize:13,color:"#64748b",textAlign:"center" }}>
        © {new Date().getFullYear()} {COMPANY}. All rights reserved. · <span style={{ color:"#c084fc",cursor:"pointer" }} onClick={()=>navigate("/TermsOfService")}>Terms of Service</span>
      </div>
    </div>
  );
}
